language: go
go:
  - "1.11.x"

services:
  - docker

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - go build .

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      repo: smarthut/agent
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
